plugin:
    name: 'pensoft.media::lang.plugin.name'
    description: 'pensoft.media::lang.plugin.description'
    author: Pensoft
    icon: oc-icon-play-circle-o
    homepage: ''
navigation:
    media-center:
        label: 'Media center'
        url: pensoft/media/logos
        icon: oc-icon-play-circle-o
        sideMenu:
            side-menu-media-logos:
                label: Logos
                url: pensoft/media/logos
                icon: oc-icon-file-image-o
            side-menu-media-flyers:
                label: Flyers
                url: pensoft/media/flyers
                icon: oc-icon-image
            side-menu-media-categories:
                label: 'Flyers Categories'
                url: pensoft/media/categories
                icon: icon-list
            side-menu-media-newsletter:
                label: Newsletter
                url: pensoft/media/newsletter
                icon: oc-icon-newspaper-o
            side-menu-media-presentations:
                label: Presentations
                url: pensoft/media/presentations
                icon: oc-icon-file-powerpoint-o
            side-menu-media-pressreleases:
                label: 'Press Releases'
                url: pensoft/media/pressreleases
                icon: oc-icon-twitch
            side-menu-item3:
                label: 'Press Releases Categories'
                url: pensoft/media/presscategories
                icon: icon-list
            side-menu-media-videos:
                label: Videos
                url: pensoft/media/videos
                icon: oc-icon-video-camera
            side-menu-item2:
                label: 'Videos Categories'
                url: pensoft/media/videoscategories
                icon: icon-list
            side-menu-media-webinars:
                label: Webinars
                url: pensoft/media/webinars
                icon: oc-icon-headphones
            side-menu-media-categories-webinars:
                label: 'Webinars Categories'
                url: pensoft/media/webinarscategories
                icon: icon-list
            side-menu-item:
                label: Graphics
                url: pensoft/media/graphics
                icon: icon-file-image-o
            side-menu-media-galleries:
                label: Galleries
                url: pensoft/media/galleries
                icon: oc-icon-camera
            side-menu-media-documents:
                label: Documents
                url: pensoft/media/documents
                icon: icon-file
