name: Presentations
form: $/pensoft/media/models/presentations/fields.yaml
modelClass: Pensoft\Media\Models\Presentations
defaultRedirect: pensoft/media/presentations
create:
    redirect: 'pensoft/media/presentations/update/:id'
    redirectClose: pensoft/media/presentations
update:
    redirect: pensoft/media/presentations
    redirectClose: pensoft/media/presentations
