list: $/pensoft/media/models/documents/columns.yaml
modelClass: Pensoft\Media\Models\Documents
title: Documents
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/media/documents/update/:id'
