list: $/pensoft/media/models/graphic/columns.yaml
modelClass: Pensoft\Media\Models\Graphic
title: Graphics
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/media/graphics/update/:id'
